cn:
  hxh:
    name: shanks

server:
  port: 9443
  ssl:
    key-store: classpath:tomcat.keystore
    key-store-password: tomcat
    keyStoreType: pkcs12
    keyAlias: tomcat
  tomcat:
    accesslog:
      buffered: true
      enabled: true
      pattern: common
      directory: log
    basedir: ./tomcat

spring:
  thymeleaf:
    cache: false
    mode: HTML

spring:
  security:
    user:
      name: hxh
      password: shankshh

logging:
  file:
    max-history: 10
    max-size: 20mb
  file: ./log/own_use.log

security:
  csrf: false

